version: '3'
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - backend
    networks:
    - project_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./Backend/db.sqlite:/app/db.sqlite
    networks:
      - project_network


volumes:
  db-data:
networks:
  project_network:

