name: Linter

on:
  workflow_dispatch:
   inputs:
    tag:
     description: 'Linter-Image tag'
     default: 'Linter-latest'
  pull_request: 
    branches:
      - main
      - develop
      - 'hotfixes/**'
    paths:
      - '**'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Run Super-Linter
       id: super-linter
       uses: github/super-linter@v5
       env:
         VALIDATE_DOCKERFILE: false

